"""rumorid

Revision ID: 20d2e943a3fc
Revises: 9065ef5b8675
Create Date: 2022-05-25 15:00:17.191961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d2e943a3fc'
down_revision = '9065ef5b8675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('rumorid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'rumorid')
    # ### end Alembic commands ###
