"""add ifrumorrnn and time

Revision ID: 318f15132e2f
Revises: 00e632380c47
Create Date: 2022-04-19 19:48:21.417880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '318f15132e2f'
down_revision = '00e632380c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('ifrumor_RNN', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('time', sa.Integer(), nullable=True))
    op.drop_column('article', 'times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('times', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('article', 'time')
    op.drop_column('article', 'ifrumor_RNN')
    # ### end Alembic commands ###
