"""Initial migration.

Revision ID: 464fca3c6e61
Revises: 
Create Date: 2022-04-06 12:21:46.643664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464fca3c6e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_to_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_reply_id'), 'post', ['reply_id'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['user_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_reply_id'), table_name='post')
    op.drop_column('post', 'reply_id')
    op.drop_column('post', 'user_to_id')
    # ### end Alembic commands ###
