"""longbody

Revision ID: 9065ef5b8675
Revises: 318f15132e2f
Create Date: 2022-04-19 19:56:34.085808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9065ef5b8675'
down_revision = '318f15132e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('longbody', sa.String(length=4000), nullable=True))
    op.drop_column('article', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', mysql.VARCHAR(length=140), nullable=True))
    op.drop_column('article', 'longbody')
    # ### end Alembic commands ###
