"""time change

Revision ID: ecc628163870
Revises: 464fca3c6e61
Create Date: 2022-04-06 14:48:53.961820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc628163870'
down_revision = '464fca3c6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('times', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'times')
    # ### end Alembic commands ###
